//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.TempDLs = new HashSet<TempDL>();
        }
    
        public int Bill_ID { get; set; }
        public System.DateTime Bill_Date { get; set; }
        public int Bill_ProductID { get; set; }
        public int Bill_Seller { get; set; }
        public int Bill_Buyer { get; set; }
        public int Bill_PayPrice { get; set; }
        public int Bill_Postage { get; set; }
        public string InvoiceNumber { get; set; }
        public string Bill_TransNo { get; set; }
        public string Bill_RefNo { get; set; }
        public Nullable<bool> Bill_Status { get; set; }
        public string Bill_TracingCode { get; set; }
        public Nullable<int> Bill_PostStatsID { get; set; }
        public int Bill_Price { get; set; }
        public System.DateTime Bill_ExpDate { get; set; }
        public int Bill_Count { get; set; }
    
        public virtual PostStatu PostStatu { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TempDL> TempDLs { get; set; }
    }
}
