//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmEmail
    {
        public int ConfirmEmail_ID { get; set; }
        public System.DateTime ConfirmEmail_Date { get; set; }
        public int ConfirmEmail_UserID { get; set; }
        public bool ConfirmEmail_Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
