//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public int Download_ID { get; set; }
        public string Download_Url { get; set; }
        public System.DateTime Download_Date { get; set; }
        public int Download_Lenght { get; set; }
        public bool Download_Allow { get; set; }
        public int Download_UserID { get; set; }
        public Nullable<int> Download_ProductID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
