//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Group_ID { get; set; }
        public string Group_Name { get; set; }
        public string Group_Pic { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
