//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identity
    {
        public int Identity_ID { get; set; }
        public string Identity_Pic { get; set; }
        public string Identity_FathersName { get; set; }
        public string Identity_Birth { get; set; }
        public bool Identity_Confirm { get; set; }
        public int Identity_UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
