//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterimBill
    {
        public int InterimBill_ID { get; set; }
        public System.DateTime InterimBill_Date { get; set; }
        public int InterimBill_ProductID { get; set; }
        public string InterimBill_Seller { get; set; }
        public int InterimBill_PayPrice { get; set; }
        public Nullable<int> InterimBill_Postage { get; set; }
        public int InterimBill_Buyer { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InterimBill_ExpDate { get; set; }
        public Nullable<int> InterimBill_Count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
