//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Massage
    {
        public int Massage_ID { get; set; }
        public int Massage_UserGet { get; set; }
        public Nullable<int> Massage_UserSend { get; set; }
        public System.DateTime Massage_Date { get; set; }
        public bool Massage_Read { get; set; }
        public string Massage_Title { get; set; }
        public string Massage_Body { get; set; }
    
        public virtual User User { get; set; }
    }
}
