//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoBank
    {
        public int Banks_ID { get; set; }
        public string Banks_NoCart { get; set; }
        public string Banks_NoIR { get; set; }
        public string Banks_NoBank { get; set; }
        public int Banks_NameID { get; set; }
        public int Banks_UserID { get; set; }
        public string Banks_NameUser { get; set; }
    
        public virtual BankName BankName { get; set; }
        public virtual User User { get; set; }
    }
}
