//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Bills = new HashSet<Bill>();
            this.Downloads = new HashSet<Download>();
            this.InterimBills = new HashSet<InterimBill>();
            this.Pics = new HashSet<Pic>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Text { get; set; }
        public int Product_Price { get; set; }
        public Nullable<int> Product_Off { get; set; }
        public string Product_PicIndex { get; set; }
        public bool Product_IsDownload { get; set; }
        public System.DateTime Product_Date { get; set; }
        public Nullable<int> Product_GroupID { get; set; }
        public bool Product_AllOff { get; set; }
        public int Product_Visit { get; set; }
        public Nullable<int> Product_ExitCount { get; set; }
        public Nullable<int> Product_Weight { get; set; }
        public int Product_UserID { get; set; }
        public bool Product_Active { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<Download> Downloads { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<InterimBill> InterimBills { get; set; }
        public virtual ICollection<Pic> Pics { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
