//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempDL
    {
        public int TempDL_ID { get; set; }
        public System.DateTime TempDL_Date { get; set; }
        public System.DateTime TempDL_ExpDate { get; set; }
        public string TempDL_UnigNo { get; set; }
        public int TempDL_BillNo { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
