//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Visit_ID { get; set; }
        public System.DateTime Visit_Date { get; set; }
        public string Visit_IP { get; set; }
        public string Visit_UserName { get; set; }
        public string Visit_Browser { get; set; }
    }
}
