//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoovinData.Models.Domin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weight
    {
        public int Weight_ID { get; set; }
        public Nullable<int> Weight_Max { get; set; }
        public Nullable<int> Weight_Min { get; set; }
        public Nullable<int> Weight_Price { get; set; }
    }
}
